use_frameworks!

platform :ios, ‘8.0’

target ’CoolGame’ do
    
pod 'SwifterSwift', '~> 1.2.2'
    
pod 'Alamofire', '~> 4.2.0'

pod 'SwiftSocket', '~> 1.2'

pod 'SwiftyJSON', '~> 3.1.3'

pod 'KeychainSwift', '~> 7.0.0'

pod 'Reveal-iOS-SDK', :configurations => ['Debug']


end
